/*
Separa os públicos

Ju Lopes
23/01/2018
*/

--Mes nascimento
DECLARE @MesNascimento INT
	SET @MesNascimento = 3

DROP TABLE  JOBS..ANIVERSARIANTES_MAR2018
	SELECT *,
		ROW_NUMBER() OVER  (PARTITION BY CELULARTRATADO ORDER BY DTCADASTRO DESC) Dedup
	INTO JOBS..ANIVERSARIANTES_MAR2018
	FROM MagazinePortal..gc_clientes (NOLOCK)
	WHERE 
		MONTH (DataNascimento) = @MesNascimento  AND
		Fl_FuncionarioID = 0 AND
		FL_SMS_Valido = 1	   AND
		(CLIENTEOURO = 'SIM' OR CLUSTER = 'CLIENTES ALTA PERFORMANCE - SUPER NÃO OURO')   AND
	   (ATIVO ='SIM' OR (ATIVO = 'NÃO' AND DTULTIMACOMPRA > DATEADD(MONTH,-18,GETDATE()-2)))

 		  
		  
--Separa público - Ouro e Não Ouro
ALTER TABLE JOBS..ANIVERSARIANTES_MAR2018 ADD Publico VARCHAR(100)
	
	--1- TODOS OS CLIENTES ALTA, ALTÍSSIMA QUE POSSUEM FILTROS DE SMS VÁLIDOS E NÃO ESTÃO RELACIONADOS NO ÍTEM 1 - SMS
UPDATE	A
SET		A.PUBLICO = 'P1 - TODOS OS CLIENTES ALTA, ALTÍSSIMA QUE POSSUEM FILTROS DE SMS VÁLIDOS - SMS'
FROM	JOBS..ANIVERSARIANTES_MAR2018 AS A
WHERE	A.CLUSTER IN ('OURO ALTA PERFORMANCE','OURO ALTÍSSIMA PERFORMANCE') 
        AND	A.PUBLICO IS NULL  


--2- TODOS OS CLIENTES DO CLUSTER SUPER NÃO OURO  QUE POSSUEM FILTROS DE SMS VÁLIDOS - SMS
UPDATE	A
SET		A.PUBLICO = 'P2 - TODOS OS CLIENTES DO CLUSTER SUPER NÃO OURO  QUE POSSUEM FILTROS DE SMS VÁLIDOS - SMS'
FROM	JOBS..ANIVERSARIANTES_MAR2018 AS A
WHERE	A.CLUSTER IN ('CLIENTES ALTA PERFORMANCE - SUPER NÃO OURO') 
		AND	A.PUBLICO IS NULL 
		

--3- CLIENTES DOS OUTROS CLUSTES OURO NÃO LISTADOS ACIMA COM FILTROS DE SMS VÁLIDOS - SMS
UPDATE	A
SET		A.PUBLICO = 'P3 - CLIENTES DOS OUTROS CLUSTES OURO NÃO LISTADOS ACIMA COM FILTROS DE SMS VÁLIDOS - SMS'
FROM	JOBS..ANIVERSARIANTES_MAR2018 AS A
WHERE	A.CLUSTER <> ('CLIENTES ALTA PERFORMANCE - SUPER NÃO OURO') 
		AND	A.PUBLICO IS NULL 
		
		  
--Adiciona os anos e a data de aniversário do cliente	
ALTER TABLE JOBS..ANIVERSARIANTES_MAR2018 ADD ANOS INT, ANIVERSARIO DATETIME	

DECLARE @Date DATETIME = '2018-03-01'

	--Atualiza anos do cliente
	UPDATE JOBS..ANIVERSARIANTES_MAR2018
	SET		ANOS = DATEDIFF(YEAR,DATANASCIMENTO, @Date) 

	--Atualiza data de aniversário
	UPDATE JOBS..ANIVERSARIANTES_MAR2018
	SET		ANIVERSARIO = DATEADD(YEAR,ANOS,DATANASCIMENTO)
	
	-- Homologando
	/*  SELECT DISTINCT DataNascimento, anos, aniversario
		FROM JOBS..ANIVERSARIANTES_MAR2018 
		  */
		
		
 --Separa controle 	 
 EXEC Jobs.DBO.SeparaGrupoControle 'JOBS..ANIVERSARIANTES_MAR2018', 35
 
   ALTER TABLE JOBS..ANIVERSARIANTES_MAR2018 DROP COLUMN FLAGCONTROLE 
		
  SELECT FLAGCONTROLE, COUNT(NUMDBM)
  FROM JOBS..ANIVERSARIANTES_MAR2018 
  GROUP BY FLAGCONTROLE
  


--Extração 
DECLARE @QUERY VARCHAR(MAX)			= 'SELECT   CodCli, 
												DigitoCliente, 
												primeiro_nome, 
												CelularTratado, 
												FilialCompraID AS Filial, 
												DAY(ANIVERSARIO) AS DIA_NASCIMENTO
										FROM JOBS..ANIVERSARIANTES_MAR2018
										WHERE FlagControle = ''n'' '
DECLARE @LAYOUT		VARCHAR(255)	= 'SMS Aniversariantes - Março'
DECLARE @CAMINHO	VARCHAR(255)	= '\\fssp\marketdata\Dados\DBM\Aniversariantes\2018\03 - Março\'
EXEC MAGAZINELUIZA.DBO.EXPORTBCP @QUERY,	@CAMINHO,	@LAYOUT, 0,	'TXT',	'|',	1
GO

--Marca campanha										  
DECLARE  @NOMELISTABUMER	VARCHAR(100)= 'SMS Aniversariantes - Março'
DECLARE  @DESCLISTABUMER	VARCHAR(100)= 'SMS Aniversariantes - Março'
DECLARE  @DTINI				DATETIME	= '2017-03-01'
DECLARE  @DTFIM				DATETIME	= '2017-03-31'
DECLARE  @TABELABUMER		VARCHAR(100)= 'JOBS..ANIVERSARIANTES_MAR2018'
DECLARE	 @MESBASE			VARCHAR(10) = '2018-02'
								  							  
EXEC MAGAZINEPORTAL.DBO.SP_MARCA_CAMPANHA_ADHOC
 3										-- 1-MALA DIRETA/2-TELEMARKETING/3-SMS/4-EMAIL/5-TELEMARKETING ANIVERSÁRIO/6-ESTUDO/9-WHATSAPP
,@NOMELISTABUMER						-- NOME DA CAMPANHA
,@DESCLISTABUMER						-- DESCRICAO DA CAMPANHA
,'Aline/Camila'								-- RESPONSAVEL, QUEM PEDIU A CAMPANHA
,'Juliana'								-- USUARIO QUE EXECUTOU A CAMPANHA
,@DTINI									-- DATA DE INICIO DA CAMPANHA AAAA-MM-DD
,@DTFIM									-- DATA DE TERMINO DA CAMAPNHA AAAA-MM-DD
,@DTINI									-- DATA DA EXTRACAO DA CAMPANHA AAAA-MM-DD
,@DTINI									-- DATA DE CRIACAO DA CAMPANHA AAAA-MM-DD
,NULL									-- CODI DA CAMPANHA DO MAGAZINE LUIZA
,NULL									-- LINHA DA CAMPANHA (EX: ELETRO PESADO)
,NULL									-- FAMILIA DA CAMPANHA (EX: REFRIGERADOR)
,@DTINI									-- DIA INICIAL DE VENDA
,@DTFIM									-- DIA FINAL DE VENDA
,@MESBASE								-- AAAA-MM REFERENCIA DA CARGA ##** ESTE CAMPO TEM QUE TER 3 ASPAS SIMPLES
,@TABELABUMER							-- NOME DA TABELA DA CAMPANHA GERADA
,NULL									-- FILIAL PAI
,1										-- FL_CUSTO: 1 - MARKETING | 2 - Extra (ex: LOJA, PROPAGANDA) | 3 - NÃO INFORMADO
,201803									-- Competência